#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PORT="${1:-8080}"
API_KEY="${2:-elec0138-demo-key}"

export THERMOSTAT_PORT="$PORT"
export THERMOSTAT_API_KEY="$API_KEY"
export THERMOSTAT_STATUS_LIMIT_COUNT="${THERMOSTAT_STATUS_LIMIT_COUNT:-20}"
export THERMOSTAT_STATUS_LIMIT_SECONDS="${THERMOSTAT_STATUS_LIMIT_SECONDS:-2}"
export THERMOSTAT_COMMAND_LIMIT_COUNT="${THERMOSTAT_COMMAND_LIMIT_COUNT:-5}"
export THERMOSTAT_COMMAND_LIMIT_SECONDS="${THERMOSTAT_COMMAND_LIMIT_SECONDS:-30}"
export THERMOSTAT_AUTH_FAIL_THRESHOLD="${THERMOSTAT_AUTH_FAIL_THRESHOLD:-3}"
export THERMOSTAT_AUTH_FAIL_WINDOW_SECONDS="${THERMOSTAT_AUTH_FAIL_WINDOW_SECONDS:-60}"
export THERMOSTAT_AUTH_FAIL_LOCK_SECONDS="${THERMOSTAT_AUTH_FAIL_LOCK_SECONDS:-60}"

echo "[*] Defended thermostat listening on 0.0.0.0:$PORT"
echo "[*] Endpoints: /status, /set_temp?value=23, /admin/metrics"
echo "[*] API key: $API_KEY"

python3 "$SCRIPT_DIR/defended_thermostat.py"
